#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Sun Feb 21 18:24:20 2010

import wx

# begin wxGlade: extracode
# end wxGlade



class MainWindow(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainWindow.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.splitter = wx.SplitterWindow(self, -1, style=wx.SP_3D|wx.SP_BORDER)
        self.playlists = customListCtrl(self.splitter, -1, style=wx.LC_REPORT|wx.LC_SINGLE_SEL|wx.SUNKEN_BORDER)
        self.games = customListCtrl(self.splitter, -1, style=wx.LC_REPORT|wx.LC_SINGLE_SEL|wx.LC_VIRTUAL|wx.LC_NO_HEADER|wx.SUNKEN_BORDER)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainWindow.__set_properties
        self.SetTitle("frame_2")
        self.SetSize((723, 569))
        self.SetMenuBar(MainMenu())
        self.playlists.SetBackgroundColour(wx.Colour(20, 20, 20))
        self.playlists.SetForegroundColour(wx.Colour(192, 192, 192))
        self.playlists.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.playlists.SetFocus()
        self.games.SetBackgroundColour(wx.Colour(20, 20, 20))
        self.games.SetForegroundColour(wx.Colour(192, 192, 192))
        self.games.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainWindow.__do_layout
        sizer = wx.BoxSizer(wx.HORIZONTAL)
        self.splitter.SplitVertically(self.playlists, self.games, 250)
        sizer.Add(self.splitter, 1, wx.EXPAND, 0)
        self.SetSizer(sizer)
        self.Layout()
        # end wxGlade

# end of class MainWindow


class MainMenu(wx.MenuBar):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainMenu.__init__
        wx.MenuBar.__init__(self, *args, **kwds)
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.NewId(), "E&xit", "", wx.ITEM_NORMAL)
        self.Append(wxglade_tmp_menu, "&File")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainMenu.__set_properties
        pass
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainMenu.__do_layout
        pass
        # end wxGlade

# end of class MainMenu


class MyApp(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        mainwnd = MainWindow(None, -1, "")
        self.SetTopWindow(mainwnd)
        mainwnd.Show()
        return 1

# end of class MyApp

if __name__ == "__main__":
    Toybocks = MyApp(0)
    Toybocks.MainLoop()
